workers_dev = true
name = "shadcn-clerk-supa"
compatibility_date = "2025-03-12"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1